version: '3.9'

services:
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./.data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=blueprint
